<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nacos.proto

namespace Hyperf\Nacos\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Payload</code>
 */
class Payload extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Metadata metadata = 2;</code>
     */
    protected $metadata = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Any body = 3;</code>
     */
    protected $body = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Hyperf\Nacos\Protobuf\Metadata $metadata
     *     @type \Hyperf\Nacos\Protobuf\Any $body
     * }
     */
    public function __construct($data = NULL) {
        \Hyperf\Nacos\Protobuf\GPBMetadata\Nacos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Metadata metadata = 2;</code>
     * @return \Hyperf\Nacos\Protobuf\Metadata|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Generated from protobuf field <code>.Metadata metadata = 2;</code>
     * @param \Hyperf\Nacos\Protobuf\Metadata $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Hyperf\Nacos\Protobuf\Metadata::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any body = 3;</code>
     * @return \Hyperf\Nacos\Protobuf\Any|null
     */
    public function getBody()
    {
        return $this->body;
    }

    public function hasBody()
    {
        return isset($this->body);
    }

    public function clearBody()
    {
        unset($this->body);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any body = 3;</code>
     * @param \Hyperf\Nacos\Protobuf\Any $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkMessage($var, \Hyperf\Nacos\Protobuf\Any::class);
        $this->body = $var;

        return $this;
    }

}

